---

- hosts: all
  become: true
  tasks:
  
  - name: install htop
    apt: 
      name: htop
      state: latest
      update_cache: yes

  - name: create devops
    user:
      name: devops
      uid: 178
  
#ansible-playbook "playbook" --ask-become-pass