---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  
  - name: install nmap package
    apt:
      name: nmap
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]  
  
  