---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and nmap package
    apt:
      name: 
        - apache2
        - nmap
        - mariadb-server
        
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]  
  
  #- name: install nmap package
   # apt:
    #  name: nmap
     # state: latest
    
  