---

- hosts: all
  become: true
  tasks:

  - name: install apache2, nmap package and mariadb
    apt:
      name: 
        - apache2
        - nmap
        - mariadb-server
        
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]  
  
  #- name: install nmap package
   # apt:
    #  name: nmap
     # state: latest

  - name: copy html file to webserver
    copy: 
      src: test.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644