---

- hosts: all
  become: true
  tasks:
  
  - name: install htop
    apt: 
      name: 
        - htop
        - nginx
      state: latest
      update_cache: yes
  - name: start nginx
    service: 
      name: nginx
      state: restarted

  - name: create devops
    user:
      name: devops
      uid: 178
  
#ansible-playbook "playbook" --ask-become-pass